version: "3"

services:
  reddit-bot:
    image: reddit-bot:latest
    build:
      context: ..
      dockerfile: build/package/Dockerfile
    container_name: reddit-bot
    restart: always
    volumes:
      - ./data/reddit-bot/etc:/etc/reddit-bot
    environment:
      - REDDITBOT_DISCORD_TOKEN=${DISCORD_TOKEN}
      - REDDITBOT_LOG_LEVEL=info