version: "3"

services:
  reddit-bot:
    image: reddit-bot:${IMAGE_TAG}
    container_name: reddit-bot
    restart: always
    volumes:
      - ./data/reddit-bot/etc:/etc/reddit-bot
    environment:
      - REDDITBOT_DISCORD_TOKEN=${DISCORD_TOKEN}
